resources:
- name: codesonar-plugin
  type: git
  source:
    uri: https://github.com/Praqma/codesonar-plugin.git
    branch: master

jobs:
- name: unit-tests
  plan:
  - get: codesonar-plugin
    trigger: true
  - task: unit-tests
    config:
     platform: linux
     image_resource:
       type: docker-image
       source:
          repository: maven
          tag: '3-jdk-8' 
     inputs:
       - name: codesonar-plugin
     run:
       path: sh
       args:
       - -exc
       - |
        ls
        cd codesonar-plugin
        
        mvn clean compile test-compile cobertura:cobertura
         
        
  