name: Java CI with Maven

on:
  push:
    branches:
      - master
      - gtmaster
  pull_request:
    branches:
      - master
      - gtmaster

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java:
          - 17
          - 21
    name: Java ${{ matrix.java }} compile
    steps:
      - uses: actions/checkout@v4

      - name: Cache maven dependencies
        uses: actions/cache@v4
        env:
          cache-name: cache-maven-dependencies
        with:
          path: ~/.m2
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: ${{ matrix.java }}

      - run: mvn test spotbugs:check
